-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module NotificationsApi.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import NotificationsApi.InputObject
import NotificationsApi.Interface
import NotificationsApi.Object
import NotificationsApi.Scalar
import NotificationsApi.ScalarCodecs
import NotificationsApi.Union


type alias SendNotificationRequiredArguments =
    { channel : String
    , from : String
    , message : String
    }


sendNotification : SendNotificationRequiredArguments -> SelectionSet decodesTo NotificationsApi.Object.Notification -> SelectionSet decodesTo RootMutation
sendNotification requiredArgs object_ =
    Object.selectionForCompositeField "sendNotification" [ Argument.required "channel" requiredArgs.channel Encode.string, Argument.required "from" requiredArgs.from Encode.string, Argument.required "message" requiredArgs.message Encode.string ] object_ identity
