-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module NotificationsApi.Query exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import NotificationsApi.InputObject
import NotificationsApi.Interface
import NotificationsApi.Object
import NotificationsApi.Scalar
import NotificationsApi.ScalarCodecs
import NotificationsApi.Union


default : SelectionSet String RootQuery
default =
    Object.selectionForField "String" "default" [] Decode.string
