-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module NotificationsApi.Subscription exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import NotificationsApi.InputObject
import NotificationsApi.Interface
import NotificationsApi.Object
import NotificationsApi.Scalar
import NotificationsApi.ScalarCodecs
import NotificationsApi.Union


type alias NotificationReceivedRequiredArguments =
    { channel : String }


notificationReceived : NotificationReceivedRequiredArguments -> SelectionSet decodesTo NotificationsApi.Object.Notification -> SelectionSet decodesTo RootSubscription
notificationReceived requiredArgs object_ =
    Object.selectionForCompositeField "notificationReceived" [ Argument.required "channel" requiredArgs.channel Encode.string ] object_ identity
